export interface IconDef {
  name: string;
  label: string;
  prefix?: string;
}

export interface IconCategory {
  id: string;
  label: string;
  icons: IconDef[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: 'ui',
    label: 'Giao diện',
    icons: [
      { name: 'house',                 label: 'Trang chủ' },
      { name: 'magnifying-glass',      label: 'Tìm kiếm' },
      { name: 'bars',                  label: 'Menu' },
      { name: 'xmark',                 label: 'Đóng' },
      { name: 'check',                 label: 'Xác nhận' },
      { name: 'plus',                  label: 'Thêm' },
      { name: 'minus',                 label: 'Bớt' },
      { name: 'chevron-right',         label: 'Tiếp' },
      { name: 'chevron-down',          label: 'Xuống' },
      { name: 'chevron-left',          label: 'Lui' },
      { name: 'chevron-up',            label: 'Lên' },
      { name: 'arrow-right',           label: 'Mũi tên phải' },
      { name: 'arrow-left',            label: 'Mũi tên trái' },
      { name: 'arrow-up',              label: 'Mũi tên lên' },
      { name: 'arrow-down',            label: 'Mũi tên xuống' },
      { name: 'eye',                   label: 'Xem' },
      { name: 'eye-slash',             label: 'Ẩn' },
      { name: 'lock',                  label: 'Khoá' },
      { name: 'unlock',                label: 'Mở khoá' },
      { name: 'gear',                  label: 'Cài đặt' },
      { name: 'sliders',               label: 'Bộ lọc' },
      { name: 'filter',                label: 'Lọc' },
      { name: 'ellipsis',              label: 'Tuỳ chọn' },
      { name: 'ellipsis-vertical',     label: 'Tuỳ chọn dọc' },
    ],
  },
  {
    id: 'communication',
    label: 'Liên lạc',
    icons: [
      { name: 'phone',                 label: 'Điện thoại' },
      { name: 'phone-flip',            label: 'Gọi điện' },
      { name: 'envelope',              label: 'Email' },
      { name: 'envelope-open',         label: 'Mở email' },
      { name: 'location-dot',          label: 'Địa chỉ' },
      { name: 'map',                   label: 'Bản đồ' },
      { name: 'comment',               label: 'Bình luận' },
      { name: 'comments',              label: 'Tin nhắn' },
      { name: 'message',               label: 'Nhắn tin' },
      { name: 'headset',               label: 'Hỗ trợ' },
      { name: 'video',                 label: 'Video call' },
      { name: 'bell',                  label: 'Thông báo' },
      { name: 'bell-slash',            label: 'Tắt thông báo' },
      { name: 'paper-plane',           label: 'Gửi' },
      { name: 'at',                    label: 'Địa chỉ email' },
      { name: 'hashtag',               label: 'Hashtag' },
    ],
  },
  {
    id: 'social',
    label: 'Mạng xã hội',
    icons: [
      { name: 'facebook-f',    label: 'Facebook',   prefix: 'fa-brands' },
      { name: 'instagram',     label: 'Instagram',  prefix: 'fa-brands' },
      { name: 'x-twitter',     label: 'X (Twitter)',prefix: 'fa-brands' },
      { name: 'youtube',       label: 'YouTube',    prefix: 'fa-brands' },
      { name: 'linkedin-in',   label: 'LinkedIn',   prefix: 'fa-brands' },
      { name: 'tiktok',        label: 'TikTok',     prefix: 'fa-brands' },
      { name: 'telegram',      label: 'Telegram',   prefix: 'fa-brands' },
      { name: 'whatsapp',      label: 'WhatsApp',   prefix: 'fa-brands' },
      { name: 'pinterest',     label: 'Pinterest',  prefix: 'fa-brands' },
      { name: 'google',        label: 'Google',     prefix: 'fa-brands' },
      { name: 'github',        label: 'GitHub',     prefix: 'fa-brands' },
      { name: 'discord',       label: 'Discord',    prefix: 'fa-brands' },
      { name: 'spotify',       label: 'Spotify',    prefix: 'fa-brands' },
      { name: 'apple',         label: 'Apple',      prefix: 'fa-brands' },
      { name: 'android',       label: 'Android',    prefix: 'fa-brands' },
    ],
  },
  {
    id: 'business',
    label: 'Kinh doanh',
    icons: [
      { name: 'briefcase',             label: 'Công việc' },
      { name: 'chart-bar',             label: 'Biểu đồ cột' },
      { name: 'chart-line',            label: 'Biểu đồ đường' },
      { name: 'chart-pie',             label: 'Biểu đồ tròn' },
      { name: 'building',              label: 'Công ty' },
      { name: 'building-columns',      label: 'Ngân hàng' },
      { name: 'handshake',             label: 'Hợp tác' },
      { name: 'users',                 label: 'Nhóm người' },
      { name: 'user',                  label: 'Người dùng' },
      { name: 'user-tie',              label: 'Nhân viên' },
      { name: 'globe',                 label: 'Toàn cầu' },
      { name: 'trophy',                label: 'Giải thưởng' },
      { name: 'medal',                 label: 'Huy chương' },
      { name: 'award',                 label: 'Bằng khen' },
      { name: 'certificate',           label: 'Chứng chỉ' },
      { name: 'rocket',                label: 'Khởi nghiệp' },
      { name: 'lightbulb',             label: 'Ý tưởng' },
      { name: 'shield-halved',         label: 'Bảo mật' },
      { name: 'key',                   label: 'Chìa khoá' },
      { name: 'suitcase',              label: 'Hành lý' },
    ],
  },
  {
    id: 'commerce',
    label: 'Thương mại',
    icons: [
      { name: 'cart-shopping',         label: 'Giỏ hàng' },
      { name: 'bag-shopping',          label: 'Túi mua' },
      { name: 'credit-card',           label: 'Thẻ tín dụng' },
      { name: 'dollar-sign',           label: 'Tiền đô' },
      { name: 'wallet',                label: 'Ví' },
      { name: 'tag',                   label: 'Nhãn giá' },
      { name: 'tags',                  label: 'Nhãn giá' },
      { name: 'truck',                 label: 'Giao hàng' },
      { name: 'truck-fast',            label: 'Giao hỏa tốc' },
      { name: 'gift',                  label: 'Quà tặng' },
      { name: 'percent',               label: 'Phần trăm' },
      { name: 'store',                 label: 'Cửa hàng' },
      { name: 'qrcode',                label: 'QR Code' },
      { name: 'barcode',               label: 'Mã vạch' },
      { name: 'receipt',               label: 'Hoá đơn' },
      { name: 'coins',                 label: 'Tiền xu' },
    ],
  },
  {
    id: 'content',
    label: 'Nội dung',
    icons: [
      { name: 'image',                 label: 'Ảnh' },
      { name: 'images',                label: 'Thư viện ảnh' },
      { name: 'film',                  label: 'Phim' },
      { name: 'circle-play',           label: 'Phát video' },
      { name: 'music',                 label: 'Âm nhạc' },
      { name: 'podcast',               label: 'Podcast' },
      { name: 'file-lines',            label: 'Tài liệu' },
      { name: 'file-pdf',              label: 'PDF' },
      { name: 'calendar',              label: 'Lịch' },
      { name: 'calendar-check',        label: 'Lịch xác nhận' },
      { name: 'clock',                 label: 'Đồng hồ' },
      { name: 'bookmark',              label: 'Lưu dấu' },
      { name: 'newspaper',             label: 'Báo' },
      { name: 'pen-nib',               label: 'Viết lách' },
      { name: 'book-open',             label: 'Sách' },
      { name: 'graduation-cap',        label: 'Giáo dục' },
      { name: 'download',              label: 'Tải xuống' },
      { name: 'upload',                label: 'Tải lên' },
      { name: 'share-nodes',           label: 'Chia sẻ' },
      { name: 'link',                  label: 'Liên kết' },
    ],
  },
  {
    id: 'misc',
    label: 'Khác',
    icons: [
      { name: 'heart',                 label: 'Yêu thích' },
      { name: 'star',                  label: 'Đánh giá' },
      { name: 'thumbs-up',             label: 'Thích' },
      { name: 'thumbs-down',           label: 'Không thích' },
      { name: 'fire',                  label: 'Hot' },
      { name: 'bolt',                  label: 'Nhanh' },
      { name: 'leaf',                  label: 'Xanh lá' },
      { name: 'sun',                   label: 'Mặt trời' },
      { name: 'moon',                  label: 'Mặt trăng' },
      { name: 'cloud',                 label: 'Đám mây' },
      { name: 'snowflake',             label: 'Tuyết' },
      { name: 'recycle',               label: 'Tái chế' },
      { name: 'check-circle',          label: 'Thành công' },
      { name: 'circle-xmark',          label: 'Lỗi' },
      { name: 'triangle-exclamation',  label: 'Cảnh báo' },
      { name: 'circle-info',           label: 'Thông tin' },
      { name: 'copy',                  label: 'Sao chép' },
      { name: 'trash',                 label: 'Xoá' },
      { name: 'pen-to-square',         label: 'Chỉnh sửa' },
      { name: 'rotate',                label: 'Làm mới' },
      { name: 'wand-magic-sparkles',   label: 'Ma thuật' },
      { name: 'crown',                 label: 'Vương miện' },
      { name: 'gem',                   label: 'Kim cương' },
      { name: 'code',                  label: 'Code' },
    ],
  },
];
