export interface IconDef {
  name: string;
  label: string;
  prefix?: string;
}

export interface IconCategory {
  id: string;
  label: string;
  icons: IconDef[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: 'ui',
    label: 'UI',
    icons: [
      { name: 'house',                 label: 'Home' },
      { name: 'magnifying-glass',      label: 'Search' },
      { name: 'bars',                  label: 'Menu' },
      { name: 'xmark',                 label: 'Close' },
      { name: 'check',                 label: 'Check' },
      { name: 'plus',                  label: 'Add' },
      { name: 'minus',                 label: 'Remove' },
      { name: 'chevron-right',         label: 'Next' },
      { name: 'chevron-down',          label: 'Down' },
      { name: 'chevron-left',          label: 'Back' },
      { name: 'chevron-up',            label: 'Up' },
      { name: 'arrow-right',           label: 'Arrow Right' },
      { name: 'arrow-left',            label: 'Arrow Left' },
      { name: 'arrow-up',              label: 'Arrow Up' },
      { name: 'arrow-down',            label: 'Arrow Down' },
      { name: 'eye',                   label: 'Show' },
      { name: 'eye-slash',             label: 'Hide' },
      { name: 'lock',                  label: 'Lock' },
      { name: 'unlock',                label: 'Unlock' },
      { name: 'gear',                  label: 'Settings' },
      { name: 'sliders',               label: 'Sliders' },
      { name: 'filter',                label: 'Filter' },
      { name: 'ellipsis',              label: 'Options' },
      { name: 'ellipsis-vertical',     label: 'Options Vertical' },
    ],
  },
  {
    id: 'communication',
    label: 'Communication',
    icons: [
      { name: 'phone',                 label: 'Phone' },
      { name: 'phone-flip',            label: 'Call' },
      { name: 'envelope',              label: 'Email' },
      { name: 'envelope-open',         label: 'Open Email' },
      { name: 'location-dot',          label: 'Location' },
      { name: 'map',                   label: 'Map' },
      { name: 'comment',               label: 'Comment' },
      { name: 'comments',              label: 'Messages' },
      { name: 'message',               label: 'Message' },
      { name: 'headset',               label: 'Support' },
      { name: 'video',                 label: 'Video call' },
      { name: 'bell',                  label: 'Notification' },
      { name: 'bell-slash',            label: 'Mute' },
      { name: 'paper-plane',           label: 'Send' },
      { name: 'at',                    label: 'Email Address' },
      { name: 'hashtag',               label: 'Hashtag' },
    ],
  },
  {
    id: 'social',
    label: 'Social Media',
    icons: [
      { name: 'facebook-f',    label: 'Facebook',   prefix: 'fa-brands' },
      { name: 'instagram',     label: 'Instagram',  prefix: 'fa-brands' },
      { name: 'x-twitter',     label: 'X (Twitter)',prefix: 'fa-brands' },
      { name: 'youtube',       label: 'YouTube',    prefix: 'fa-brands' },
      { name: 'linkedin-in',   label: 'LinkedIn',   prefix: 'fa-brands' },
      { name: 'tiktok',        label: 'TikTok',     prefix: 'fa-brands' },
      { name: 'telegram',      label: 'Telegram',   prefix: 'fa-brands' },
      { name: 'whatsapp',      label: 'WhatsApp',   prefix: 'fa-brands' },
      { name: 'pinterest',     label: 'Pinterest',  prefix: 'fa-brands' },
      { name: 'google',        label: 'Google',     prefix: 'fa-brands' },
      { name: 'github',        label: 'GitHub',     prefix: 'fa-brands' },
      { name: 'discord',       label: 'Discord',    prefix: 'fa-brands' },
      { name: 'spotify',       label: 'Spotify',    prefix: 'fa-brands' },
      { name: 'apple',         label: 'Apple',      prefix: 'fa-brands' },
      { name: 'android',       label: 'Android',    prefix: 'fa-brands' },
    ],
  },
  {
    id: 'business',
    label: 'Business',
    icons: [
      { name: 'briefcase',             label: 'Work' },
      { name: 'chart-bar',             label: 'Bar Chart' },
      { name: 'chart-line',            label: 'Line Chart' },
      { name: 'chart-pie',             label: 'Pie Chart' },
      { name: 'building',              label: 'Company' },
      { name: 'building-columns',      label: 'Bank' },
      { name: 'handshake',             label: 'Partnership' },
      { name: 'users',                 label: 'Team' },
      { name: 'user',                  label: 'User' },
      { name: 'user-tie',              label: 'Employee' },
      { name: 'globe',                 label: 'Global' },
      { name: 'trophy',                label: 'Trophy' },
      { name: 'medal',                 label: 'Medal' },
      { name: 'award',                 label: 'Award' },
      { name: 'certificate',           label: 'Certificate' },
      { name: 'rocket',                label: 'Startup' },
      { name: 'lightbulb',             label: 'Idea' },
      { name: 'shield-halved',         label: 'Security' },
      { name: 'key',                   label: 'Key' },
      { name: 'suitcase',              label: 'Luggage' },
    ],
  },
  {
    id: 'commerce',
    label: 'Commerce',
    icons: [
      { name: 'cart-shopping',         label: 'Cart' },
      { name: 'bag-shopping',          label: 'Shopping Bag' },
      { name: 'credit-card',           label: 'Credit Card' },
      { name: 'dollar-sign',           label: 'Dollar' },
      { name: 'wallet',                label: 'Wallet' },
      { name: 'tag',                   label: 'Price Tag' },
      { name: 'tags',                  label: 'Price Tags' },
      { name: 'truck',                 label: 'Delivery' },
      { name: 'truck-fast',            label: 'Express Delivery' },
      { name: 'gift',                  label: 'Gift' },
      { name: 'percent',               label: 'Percent' },
      { name: 'store',                 label: 'Store' },
      { name: 'qrcode',                label: 'QR Code' },
      { name: 'barcode',               label: 'Barcode' },
      { name: 'receipt',               label: 'Receipt' },
      { name: 'coins',                 label: 'Coins' },
    ],
  },
  {
    id: 'content',
    label: 'Content',
    icons: [
      { name: 'image',                 label: 'Image' },
      { name: 'images',                label: 'Gallery' },
      { name: 'film',                  label: 'Film' },
      { name: 'circle-play',           label: 'Play Video' },
      { name: 'music',                 label: 'Music' },
      { name: 'podcast',               label: 'Podcast' },
      { name: 'file-lines',            label: 'Document' },
      { name: 'file-pdf',              label: 'PDF' },
      { name: 'calendar',              label: 'Calendar' },
      { name: 'calendar-check',        label: 'Confirmed Date' },
      { name: 'clock',                 label: 'Clock' },
      { name: 'bookmark',              label: 'Bookmark' },
      { name: 'newspaper',             label: 'Newspaper' },
      { name: 'pen-nib',               label: 'Writing' },
      { name: 'book-open',             label: 'Book' },
      { name: 'graduation-cap',        label: 'Education' },
      { name: 'download',              label: 'Download' },
      { name: 'upload',                label: 'Upload' },
      { name: 'share-nodes',           label: 'Share' },
      { name: 'link',                  label: 'Link' },
    ],
  },
  {
    id: 'misc',
    label: 'Misc',
    icons: [
      { name: 'heart',                 label: 'Favorite' },
      { name: 'star',                  label: 'Rating' },
      { name: 'thumbs-up',             label: 'Like' },
      { name: 'thumbs-down',           label: 'Dislike' },
      { name: 'fire',                  label: 'Hot' },
      { name: 'bolt',                  label: 'Fast' },
      { name: 'leaf',                  label: 'Green' },
      { name: 'sun',                   label: 'Sun' },
      { name: 'moon',                  label: 'Moon' },
      { name: 'cloud',                 label: 'Cloud' },
      { name: 'snowflake',             label: 'Snowflake' },
      { name: 'recycle',               label: 'Recycle' },
      { name: 'check-circle',          label: 'Success' },
      { name: 'circle-xmark',          label: 'Error' },
      { name: 'triangle-exclamation',  label: 'Warning' },
      { name: 'circle-info',           label: 'Info' },
      { name: 'copy',                  label: 'Copy' },
      { name: 'trash',                 label: 'Delete' },
      { name: 'pen-to-square',         label: 'Edit' },
      { name: 'rotate',                label: 'Refresh' },
      { name: 'wand-magic-sparkles',   label: 'Magic' },
      { name: 'crown',                 label: 'Crown' },
      { name: 'gem',                   label: 'Gem' },
      { name: 'code',                  label: 'Code' },
    ],
  },
];
