// GrapesJS 0.22 style manager sector configuration — Vietnamese labels
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const styleSectors: any[] = [
  {
    id: 'typography',
    name: 'Kiểu chữ',
    open: true,
    properties: [
      {
        property: 'font-family',
        label: 'Font chữ',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'Arial, Helvetica, sans-serif', label: 'Arial' },
          { id: "'Times New Roman', Times, serif", label: 'Times New Roman' },
          { id: 'Georgia, serif', label: 'Georgia' },
          { id: 'Verdana, sans-serif', label: 'Verdana' },
          { id: 'Roboto, sans-serif', label: 'Roboto' },
          { id: "'Open Sans', sans-serif", label: 'Open Sans' },
          { id: "'Montserrat', sans-serif", label: 'Montserrat' },
        ],
      },
      { property: 'font-size', label: 'Cỡ chữ', type: 'integer', units: ['px', 'em', 'rem', '%'], default: '' },
      {
        property: 'font-weight',
        label: 'Độ đậm',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: '300', label: 'Nhẹ (300)' },
          { id: '400', label: 'Bình thường (400)' },
          { id: '500', label: 'Vừa (500)' },
          { id: '600', label: 'Đậm vừa (600)' },
          { id: '700', label: 'Đậm (700)' },
          { id: '800', label: 'Rất đậm (800)' },
        ],
      },
      {
        property: 'font-style',
        label: 'Nghiêng',
        type: 'radio',
        default: 'normal',
        options: [
          { id: 'normal', label: 'Thường' },
          { id: 'italic', label: 'Nghiêng' },
        ],
      },
      { property: 'color', label: 'Màu chữ', type: 'color', default: '' },
      { property: '--text-gradient', label: 'Gradient chữ', type: 'text-gradient-picker', default: '', full: true, isVisible: () => true },
      {
        property: 'text-align',
        label: 'Căn chỉnh',
        type: 'radio',
        default: '',
        options: [
          { id: 'left', label: 'Trái' },
          { id: 'center', label: 'Giữa' },
          { id: 'right', label: 'Phải' },
          { id: 'justify', label: 'Đều' },
        ],
      },
      { property: 'line-height', label: 'Khoảng cách dòng', type: 'integer', units: ['', 'px', 'em'], default: '' },
      { property: 'letter-spacing', label: 'Khoảng cách ký tự', type: 'integer', units: ['px', 'em'], default: '' },
      {
        property: 'text-decoration',
        label: 'Trang trí chữ',
        type: 'select',
        default: '',
        options: [
          { id: 'none', label: 'Không' },
          { id: 'underline', label: 'Gạch dưới' },
          { id: 'line-through', label: 'Gạch ngang' },
          { id: 'overline', label: 'Gạch trên' },
        ],
      },
      {
        property: 'text-transform',
        label: 'Chữ hoa/thường',
        type: 'select',
        default: '',
        options: [
          { id: 'none', label: 'Không' },
          { id: 'uppercase', label: 'HOA TẤT CẢ' },
          { id: 'lowercase', label: 'thường tất cả' },
          { id: 'capitalize', label: 'Viết Hoa Đầu Câu' },
        ],
      },
    ],
  },
  {
    id: 'dimension',
    name: 'Kích thước',
    open: false,
    properties: [
      { property: 'width', label: 'Chiều rộng', type: 'integer', units: ['px', '%', 'vw', 'em', 'rem'], default: '' },
      { property: 'height', label: 'Chiều cao', type: 'integer', units: ['px', '%', 'vh', 'em', 'rem'], default: '' },
      { property: 'max-width', label: 'Rộng tối đa', type: 'integer', units: ['px', '%', 'vw'], default: '' },
      { property: 'min-width', label: 'Rộng tối thiểu', type: 'integer', units: ['px', '%'], default: '' },
      { property: 'min-height', label: 'Cao tối thiểu', type: 'integer', units: ['px', '%', 'vh'], default: '' },
      {
        property: 'padding',
        label: 'Đệm trong (T/P/D/T)',
        type: 'composite',
        properties: [
          { property: 'padding-top', label: 'Trên', type: 'integer', units: ['px', 'em', '%'] },
          { property: 'padding-right', label: 'Phải', type: 'integer', units: ['px', 'em', '%'] },
          { property: 'padding-bottom', label: 'Dưới', type: 'integer', units: ['px', 'em', '%'] },
          { property: 'padding-left', label: 'Trái', type: 'integer', units: ['px', 'em', '%'] },
        ],
      },
      {
        property: 'margin',
        label: 'Lề ngoài (T/P/D/T)',
        type: 'composite',
        properties: [
          { property: 'margin-top', label: 'Trên', type: 'integer', units: ['px', 'em', '%'] },
          { property: 'margin-right', label: 'Phải', type: 'integer', units: ['px', 'em', '%'] },
          { property: 'margin-bottom', label: 'Dưới', type: 'integer', units: ['px', 'em', '%'] },
          { property: 'margin-left', label: 'Trái', type: 'integer', units: ['px', 'em', '%'] },
        ],
      },
    ],
  },
  {
    id: 'layout',
    name: 'Bố cục (Flex/Grid)',
    open: false,
    properties: [
      {
        property: 'display',
        label: 'Kiểu hiển thị',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'block', label: 'Block' },
          { id: 'flex', label: 'Flex' },
          { id: 'grid', label: 'Grid' },
          { id: 'inline-block', label: 'Inline-block' },
          { id: 'inline', label: 'Inline' },
          { id: 'none', label: 'Ẩn' },
        ],
      },
      {
        property: 'flex-direction',
        label: 'Hướng Flex',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'row', label: 'Hàng ngang →' },
          { id: 'column', label: 'Cột dọc ↓' },
          { id: 'row-reverse', label: 'Ngang (đảo) ←' },
          { id: 'column-reverse', label: 'Dọc (đảo) ↑' },
        ],
      },
      {
        property: 'flex-wrap',
        label: 'Xuống dòng',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'nowrap', label: 'Không' },
          { id: 'wrap', label: 'Có' },
        ],
      },
      {
        property: 'justify-content',
        label: 'Căn trục chính',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'flex-start', label: 'Đầu' },
          { id: 'center', label: 'Giữa' },
          { id: 'flex-end', label: 'Cuối' },
          { id: 'space-between', label: 'Đều (ngoài)' },
          { id: 'space-around', label: 'Đều (trong)' },
          { id: 'space-evenly', label: 'Đều hoàn toàn' },
        ],
      },
      {
        property: 'align-items',
        label: 'Căn trục phụ',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'flex-start', label: 'Đầu' },
          { id: 'center', label: 'Giữa' },
          { id: 'flex-end', label: 'Cuối' },
          { id: 'stretch', label: 'Kéo giãn' },
          { id: 'baseline', label: 'Đường cơ sở' },
        ],
      },
      { property: 'gap', label: 'Khoảng cách', type: 'integer', units: ['px', 'em', 'rem'], default: '' },
      { property: 'flex', label: 'Flex tỉ lệ', type: 'integer', units: [''], default: '' },
      {
        property: 'grid-template-columns',
        label: 'Grid cột',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'repeat(2, 1fr)', label: '2 cột đều' },
          { id: 'repeat(3, 1fr)', label: '3 cột đều' },
          { id: 'repeat(4, 1fr)', label: '4 cột đều' },
          { id: '1fr 2fr', label: '1/3 + 2/3' },
          { id: '2fr 1fr', label: '2/3 + 1/3' },
          { id: 'repeat(auto-fit, minmax(200px, 1fr))', label: 'Tự động (200px min)' },
        ],
      },
    ],
  },
  {
    id: 'background',
    name: 'Nền',
    open: false,
    properties: [
      { property: 'background-color', label: 'Màu nền đặc', type: 'color', default: '' },
      {
        property: 'background-image',
        label: 'Gradient nền (preset)',
        type: 'select',
        default: 'none',
        options: [
          { id: 'none', label: '— Không gradient —' },
          { id: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', label: '💜 Tím • Xanh dương' },
          { id: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', label: '🌸 Hồng • Đỏ' },
          { id: 'linear-gradient(135deg, #f6d365 0%, #fda085 100%)', label: '🌅 Vàng • Cam' },
          { id: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', label: '🌊 Xanh biển sáng' },
          { id: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)', label: '🌿 Xanh lá • Teal' },
          { id: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)', label: '🌺 Hồng • Vàng' },
          { id: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)', label: '🪻 Lavender nhạt' },
          { id: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)', label: '🌸 Hồng pastel' },
          { id: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)', label: '🍑 Đào • Cam nhạt' },
          { id: 'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)', label: '🌈 Tím • Xanh pastel' },
          { id: 'linear-gradient(135deg, #1a1a2e 0%, #0f3460 100%)', label: '🌌 Đêm tối (tím đen)' },
          { id: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)', label: '☁️ Xám trắng nhạt' },
          { id: 'linear-gradient(to right, #ff6b6b, #feca57, #48dbfb, #ff9ff3)', label: '🌈 Cầu vồng' },
          { id: 'linear-gradient(135deg, #e96c1a 0%, #c0392b 100%)', label: '🔥 Đỏ cam (lửa)' },
          { id: 'linear-gradient(135deg, #2c3e50 0%, #4ca1af 100%)', label: '🌃 Xám xanh đậm' },
        ],
      },
      // Free-text for custom gradient — leave type unset so GrapesJS renders a text input
      { property: 'background', label: 'Gradient tùy chỉnh', default: '' },
      {
        property: 'background-size',
        label: 'Kích thước ảnh nền',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'cover', label: 'Bao phủ (cover)' },
          { id: 'contain', label: 'Vừa khít (contain)' },
          { id: '100% 100%', label: 'Kéo giãn' },
          { id: 'auto', label: 'Tự động' },
        ],
      },
      {
        property: 'background-position',
        label: 'Vị trí ảnh nền',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'center', label: 'Giữa' },
          { id: 'top center', label: 'Trên giữa' },
          { id: 'bottom center', label: 'Dưới giữa' },
          { id: 'left center', label: 'Trái giữa' },
          { id: 'right center', label: 'Phải giữa' },
        ],
      },
      {
        property: 'background-repeat',
        label: 'Lặp ảnh nền',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'no-repeat', label: 'Không lặp' },
          { id: 'repeat', label: 'Lặp' },
          { id: 'repeat-x', label: 'Lặp ngang' },
          { id: 'repeat-y', label: 'Lặp dọc' },
        ],
      },
    ],
  },
  {
    id: 'border',
    name: 'Viền',
    open: false,
    properties: [
      { property: 'border-radius', label: 'Bo góc', type: 'integer', units: ['px', '%', 'em'], default: '' },
      {
        property: 'border-style',
        label: 'Kiểu viền (chọn trước)',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'none', label: 'Không' },
          { id: 'solid', label: 'Liền nét' },
          { id: 'dashed', label: 'Đứt nét' },
          { id: 'dotted', label: 'Chấm' },
          { id: 'double', label: 'Đôi' },
        ],
      },
      { property: 'border-width', label: 'Độ dày', type: 'integer', units: ['px'], default: '' },
      { property: 'border-color', label: 'Màu viền', type: 'color', default: '' },
    ],
  },
  {
    id: 'effects',
    name: 'Hiệu ứng',
    open: false,
    properties: [
      { property: 'box-shadow', label: 'Bóng đổ', type: 'shadow', default: '' },
      {
        property: 'opacity',
        label: 'Độ mờ',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định (100%)' },
          { id: '0.9', label: '90%' },
          { id: '0.8', label: '80%' },
          { id: '0.7', label: '70%' },
          { id: '0.5', label: '50%' },
          { id: '0.3', label: '30%' },
          { id: '0', label: '0% (ẩn)' },
        ],
      },
      {
        property: 'overflow',
        label: 'Nội dung tràn',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'visible', label: 'Hiển thị' },
          { id: 'hidden', label: 'Ẩn' },
          { id: 'auto', label: 'Tự động (cuộn)' },
          { id: 'scroll', label: 'Luôn cuộn' },
        ],
      },
      {
        property: 'cursor',
        label: 'Con trỏ chuột',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Mặc định' },
          { id: 'pointer', label: 'Tay chỉ' },
          { id: 'default', label: 'Mũi tên' },
          { id: 'not-allowed', label: 'Không cho phép' },
          { id: 'move', label: 'Di chuyển' },
        ],
      },
    ],
  },
]
