import { GOOGLE_FONTS } from './googleFonts';

// GrapesJS 0.22 style manager sector configuration
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const styleSectors: any[] = [
  // ── 1. Typography ────────────────────────────────────────────────────────
  {
    id: 'typography',
    name: 'Typography',
    open: true,
    properties: [
      {
        property: 'font-family',
        label: 'Font',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select font —' },
          // System fonts
          { id: 'Arial, Helvetica, sans-serif',    label: 'Arial (system)' },
          { id: "'Times New Roman', Times, serif",  label: 'Times New Roman (system)' },
          { id: 'Georgia, serif',                   label: 'Georgia (system)' },
          { id: 'Verdana, sans-serif',              label: 'Verdana (system)' },
          // Google Fonts — auto-generated from GOOGLE_FONTS list
          ...GOOGLE_FONTS.map((f) => ({
            id: `'${f.family}', ${f.category}`,
            label: `${f.label} (Google)`,
          })),
        ],
      },
      { property: 'font-size', label: 'Font Size', type: 'integer', units: ['px', 'em', 'rem', '%'], default: '', placeholder: '16' },
      {
        property: 'font-weight',
        label: 'Font Weight',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: '300', label: 'Light (300)' },
          { id: '400', label: 'Normal (400)' },
          { id: '500', label: 'Medium (500)' },
          { id: '600', label: 'Semi-bold (600)' },
          { id: '700', label: 'Bold (700)' },
          { id: '800', label: 'Extra-bold (800)' },
        ],
      },
      {
        property: 'font-style',
        label: 'Font Style',
        type: 'radio',
        default: 'normal',
        options: [
          { id: 'normal', label: 'Normal' },
          { id: 'italic', label: 'Italic' },
        ],
      },
      {
        property: 'text-align',
        label: 'Text Align',
        type: 'radio',
        default: '',
        options: [
          { id: 'left', label: 'Left' },
          { id: 'center', label: 'Center' },
          { id: 'right', label: 'Right' },
          { id: 'justify', label: 'Justify' },
        ],
      },
      { property: 'color', label: 'Text Color', type: 'color', default: '', placeholder: '#0f172a' },
      { property: '--text-gradient', label: 'Text Gradient', type: 'text-gradient-picker', default: '', full: true },
      { property: 'line-height', label: 'Line Height', type: 'integer', units: ['', 'px', 'em'], default: '', placeholder: '1.6' },
      { property: 'letter-spacing', label: 'Letter Spacing', type: 'integer', units: ['px', 'em'], default: '', placeholder: '0.05' },
      {
        property: 'text-decoration',
        label: 'Text Decoration',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'none', label: 'None' },
          { id: 'underline', label: 'Underline' },
          { id: 'line-through', label: 'Strikethrough' },
          { id: 'overline', label: 'Overline' },
        ],
      },
      {
        property: 'text-transform',
        label: 'Text Transform',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'none', label: 'None' },
          { id: 'uppercase', label: 'UPPERCASE' },
          { id: 'lowercase', label: 'lowercase' },
          { id: 'capitalize', label: 'Capitalize' },
        ],
      },
    ],
  },

  // ── 2. Background ─────────────────────────────────────────────────────────
  {
    id: 'background',
    name: 'Background',
    open: false,
    properties: [
      { property: 'background-color', label: 'Background Color', type: 'color', default: '', placeholder: '#ffffff' },
      { property: '--bg-gradient', label: 'Background Gradient', type: 'bg-gradient-picker', default: '', full: true },
      {
        property: 'background-size',
        label: 'Background Size',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'cover', label: 'Cover' },
          { id: 'contain', label: 'Contain' },
          { id: '100% 100%', label: 'Stretch' },
          { id: 'auto', label: 'Auto' },
        ],
      },
      {
        property: 'background-position',
        label: 'Background Position',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'center', label: 'Center' },
          { id: 'top center', label: 'Top Center' },
          { id: 'bottom center', label: 'Bottom Center' },
          { id: 'left center', label: 'Left Center' },
          { id: 'right center', label: 'Right Center' },
        ],
      },
      {
        property: 'background-repeat',
        label: 'Background Repeat',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'no-repeat', label: 'No Repeat' },
          { id: 'repeat', label: 'Repeat' },
          { id: 'repeat-x', label: 'Repeat X' },
          { id: 'repeat-y', label: 'Repeat Y' },
        ],
      },
    ],
  },

  // ── 3. Dimension ─────────────────────────────────────────────────────────
  {
    id: 'dimension',
    name: 'Dimension',
    open: false,
    properties: [
      { property: 'width', label: 'Width', type: 'integer', units: ['px', '%', 'vw', 'em', 'rem'], default: '', placeholder: '100' },
      { property: 'height', label: 'Height', type: 'integer', units: ['px', '%', 'vh', 'em', 'rem'], default: '', placeholder: '300' },
      { property: 'max-width', label: 'Max Width', type: 'integer', units: ['px', '%', 'vw'], default: '', placeholder: '1200' },
      { property: 'min-width', label: 'Min Width', type: 'integer', units: ['px', '%'], default: '', placeholder: '280' },
      { property: 'min-height', label: 'Min Height', type: 'integer', units: ['px', '%', 'vh'], default: '', placeholder: '200' },
      {
        property: 'padding',
        label: 'Padding (T/R/B/L)',
        type: 'composite',
        properties: [
          { property: 'padding-top', label: 'Top', type: 'integer', units: ['px', 'em', '%'], placeholder: '24' },
          { property: 'padding-right', label: 'Right', type: 'integer', units: ['px', 'em', '%'], placeholder: '24' },
          { property: 'padding-bottom', label: 'Bottom', type: 'integer', units: ['px', 'em', '%'], placeholder: '24' },
          { property: 'padding-left', label: 'Left', type: 'integer', units: ['px', 'em', '%'], placeholder: '24' },
        ],
      },
      {
        property: 'margin',
        label: 'Margin (T/R/B/L)',
        type: 'composite',
        properties: [
          { property: 'margin-top', label: 'Top', type: 'integer', units: ['px', 'em', '%'], placeholder: '0' },
          { property: 'margin-right', label: 'Right', type: 'integer', units: ['px', 'em', '%'], placeholder: '0' },
          { property: 'margin-bottom', label: 'Bottom', type: 'integer', units: ['px', 'em', '%'], placeholder: '0' },
          { property: 'margin-left', label: 'Left', type: 'integer', units: ['px', 'em', '%'], placeholder: '0' },
        ],
      },
    ],
  },

  // ── 4. Border ─────────────────────────────────────────────────────────────
  {
    id: 'border',
    name: 'Border',
    open: false,
    properties: [
      { property: 'border-radius', label: 'Border Radius', type: 'integer', units: ['px', '%', 'em'], default: '', placeholder: '8' },
      {
        property: 'border-style',
        label: 'Border Style',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'none', label: 'None' },
          { id: 'solid', label: 'Solid' },
          { id: 'dashed', label: 'Dashed' },
          { id: 'dotted', label: 'Dotted' },
          { id: 'double', label: 'Double' },
        ],
      },
      { property: 'border-width', label: 'Border Width', type: 'integer', units: ['px'], default: '', placeholder: '2' },
      { property: 'border-color', label: 'Border Color', type: 'color', default: '', placeholder: '#e2e8f0' },
    ],
  },

  // ── 5. Layout ─────────────────────────────────────────────────────────────
  {
    id: 'layout',
    name: 'Layout (Flex/Grid)',
    open: false,
    properties: [
      {
        property: 'display',
        label: 'Display',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'block', label: 'Block' },
          { id: 'flex', label: 'Flex' },
          { id: 'grid', label: 'Grid' },
          { id: 'inline-block', label: 'Inline-block' },
          { id: 'inline', label: 'Inline' },
          { id: 'none', label: 'Hidden' },
        ],
      },
      {
        property: 'flex-direction',
        label: 'Flex Direction',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'row', label: 'Row →' },
          { id: 'column', label: 'Column ↓' },
          { id: 'row-reverse', label: 'Row Reverse ←' },
          { id: 'column-reverse', label: 'Column Reverse ↑' },
        ],
      },
      {
        property: 'flex-wrap',
        label: 'Flex Wrap',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'nowrap', label: 'No Wrap' },
          { id: 'wrap', label: 'Wrap' },
        ],
      },
      {
        property: 'justify-content',
        label: 'Justify Content',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'flex-start', label: 'Start' },
          { id: 'center', label: 'Center' },
          { id: 'flex-end', label: 'End' },
          { id: 'space-between', label: 'Space Between' },
          { id: 'space-around', label: 'Space Around' },
          { id: 'space-evenly', label: 'Space Evenly' },
        ],
      },
      {
        property: 'align-items',
        label: 'Align Items',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'flex-start', label: 'Start' },
          { id: 'center', label: 'Center' },
          { id: 'flex-end', label: 'End' },
          { id: 'stretch', label: 'Stretch' },
          { id: 'baseline', label: 'Baseline' },
        ],
      },
      { property: 'gap', label: 'Gap', type: 'integer', units: ['px', 'em', 'rem'], default: '', placeholder: '16' },
      { property: 'flex', label: 'Flex Ratio', type: 'integer', units: [''], default: '', placeholder: '1' },
      {
        property: 'grid-template-columns',
        label: 'Grid Columns',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'repeat(2, 1fr)', label: '2 equal columns' },
          { id: 'repeat(3, 1fr)', label: '3 equal columns' },
          { id: 'repeat(4, 1fr)', label: '4 equal columns' },
          { id: '1fr 2fr', label: '1/3 + 2/3' },
          { id: '2fr 1fr', label: '2/3 + 1/3' },
          { id: 'repeat(auto-fit, minmax(200px, 1fr))', label: 'Auto (200px min)' },
        ],
      },
    ],
  },

  // ── 6. Effects ────────────────────────────────────────────────────────────
  {
    id: 'effects',
    name: 'Effects',
    open: false,
    properties: [
      {
        property: 'box-shadow',
        label: 'Box Shadow',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— None —' },
          { id: '0 1px 3px rgba(0,0,0,0.12)', label: 'Light' },
          { id: '0 4px 12px rgba(0,0,0,0.15)', label: 'Medium' },
          { id: '0 8px 24px rgba(0,0,0,0.18)', label: 'Strong' },
          { id: '0 20px 48px rgba(0,0,0,0.25)', label: 'Heavy' },
          { id: 'inset 0 2px 6px rgba(0,0,0,0.12)', label: 'Inset' },
          { id: '0 4px 16px rgba(79,70,229,0.35)', label: '🔵 Indigo' },
          { id: '0 4px 16px rgba(139,92,246,0.35)', label: '🟣 Violet' },
          { id: '0 4px 16px rgba(168,85,247,0.35)', label: '🟣 Purple' },
          { id: '0 4px 16px rgba(217,70,239,0.35)', label: '🟣 Fuchsia' },
          { id: '0 4px 16px rgba(236,72,153,0.35)', label: '🩷 Pink' },
          { id: '0 4px 16px rgba(239,68,68,0.35)', label: '🔴 Red' },
          { id: '0 4px 16px rgba(249,115,22,0.35)', label: '🟠 Orange' },
          { id: '0 4px 16px rgba(234,179,8,0.35)', label: '🟡 Yellow' },
          { id: '0 4px 16px rgba(16,185,129,0.35)', label: '🟢 Emerald' },
          { id: '0 4px 16px rgba(34,197,94,0.35)', label: '🟢 Green' },
          { id: '0 4px 16px rgba(14,165,233,0.35)', label: '🔵 Sky' },
          { id: '0 4px 16px rgba(59,130,246,0.35)', label: '🔵 Blue' },
          { id: '0 4px 16px rgba(6,182,212,0.35)', label: '🩵 Cyan' },
          { id: '0 4px 20px rgba(79,70,229,0.5), 0 8px 40px rgba(139,92,246,0.3)', label: '✨ Purple Glow' },
          { id: '0 4px 20px rgba(236,72,153,0.5), 0 8px 40px rgba(239,68,68,0.3)', label: '✨ Pink-Red Glow' },
          { id: '0 4px 20px rgba(16,185,129,0.5), 0 8px 40px rgba(14,165,233,0.3)', label: '✨ Green-Blue Glow' },
        ],
      },
      {
        property: 'opacity',
        label: 'Opacity',
        type: 'select',
        default: '',
        options: [
          { id: '', label: 'Default (100%)' },
          { id: '0.9', label: '90%' },
          { id: '0.8', label: '80%' },
          { id: '0.7', label: '70%' },
          { id: '0.5', label: '50%' },
          { id: '0.3', label: '30%' },
          { id: '0', label: '0% (hidden)' },
        ],
      },
      {
        property: 'overflow',
        label: 'Overflow',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'visible', label: 'Visible' },
          { id: 'hidden', label: 'Hidden' },
          { id: 'auto', label: 'Auto (scroll)' },
          { id: 'scroll', label: 'Always scroll' },
        ],
      },
      {
        property: 'cursor',
        label: 'Cursor',
        type: 'select',
        default: '',
        options: [
          { id: '', label: '— Select —' },
          { id: 'pointer', label: 'Pointer' },
          { id: 'default', label: 'Default' },
          { id: 'not-allowed', label: 'Not Allowed' },
          { id: 'move', label: 'Move' },
        ],
      },
    ],
  },
]
